# Copyright 2016-2024 Cloudbase Solutions Srl
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#
# Module manifest for module 'powershell-yaml'
#
# Generated by: Gabriel Adrian Samfira
#
# Generated on: 10/01/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'powershell-yaml.psm1'

# Version number of this module.
ModuleVersion = '0.4.12'

PrivateData = @{
    PSData = @{
        LicenseUri   = 'https://github.com/cloudbase/powershell-yaml/blob/master/LICENSE'
        ProjectUri   = 'https://github.com/cloudbase/powershell-yaml'
        ReleaseNotes = @'
# 0.4.12

Bugfixes:
* Fix potential erroneous load of assembly by @gabriel-samfira in https://github.com/cloudbase/powershell-yaml/pull/180

# 0.4.11

Bugfixes:
* Fix nested PSCustomObjects in hashtables by @gabriel-samfira in https://github.com/cloudbase/powershell-yaml/pull/169
* Use decimal as first option when parsing floats by @gabriel-samfira in https://github.com/cloudbase/powershell-yaml/pull/170. Thanks @amis92 for the suggestion!
* Fix lint errors by @gabriel-samfira in https://github.com/cloudbase/powershell-yaml/pull/172
* Use decimals instead of double for tagged floats by @gabriel-samfira in https://github.com/cloudbase/powershell-yaml/pull/174

Misc:
* Add aditional tests by @gabriel-samfira in https://github.com/cloudbase/powershell-yaml/pull/171
* Update README.md by @gabriel-samfira in https://github.com/cloudbase/powershell-yaml/pull/173

# 0.4.10

Bugfixes:
* A broken if statement mistakingly considered 0 as false and converted a 0 valued int to BigInteger (https://github.com/cloudbase/powershell-yaml/pull/165).
* Fixes JSONCompatible flag after we implemented an IDictionary and PSCustomObject type converters (https://github.com/cloudbase/powershell-yaml/pull/166).

# 0.4.9

Changes in this version:
* Revert commit 7980c7c "Fix losing case sensitive keys" (https://github.com/cloudbase/powershell-yaml/pull/159) . This change added a breaking change which was not properly documented before release, breaking some applications. This change will be re-added in a later version.
* Unwrap PScustomObjects before serializing (https://github.com/cloudbase/powershell-yaml/pull/158)
'@
    }
}

# ID used to uniquely identify this module
GUID = '6a75a662-7f53-425a-9777-ee61284407da'

# Author of this module
Author = 'Gabriel Adrian Samfira','Alessandro Pilotti'

# Company or vendor of this module
CompanyName = 'Cloudbase Solutions SRL'

# Copyright statement for this module
Copyright = '(c) 2016-2024 Cloudbase Solutions SRL. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Powershell module for serializing and deserializing YAML'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# Functions to export from this module
FunctionsToExport = "ConvertTo-Yaml","ConvertFrom-Yaml"

AliasesToExport = "cfy","cty"
}
